name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: 🧶 Set up Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🛠️ Build monorepo (via Turbo or workspaces)
        run: yarn build
        env:
          DATABASE_DIRECT_URL: ${{ secrets.DATABASE_DIRECT_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          CALENDSO_ENCRYPTION_KEY: ${{ secrets.CALENDSO_ENCRYPTION_KEY }}
          NEXT_PUBLIC_API_V2_URL: ${{ secrets.NEXT_PUBLIC_API_V2_URL }}
          CALCOM_PRIVATE_API_ROUTE: ${{ var.CALCOM_PRIVATE_API_ROUTE }}
          NEXT_PUBLIC_WEBAPP_URL: ${{ var.NEXT_PUBLIC_WEBAPP_URL }}
          NEXT_PUBLIC_WEBSITE_URL: ${{ var.NEXT_PUBLIC_WEBSITE_URL }}
          NEXT_PUBLIC_CONSOLE_URL: ${{ var.NEXT_PUBLIC_CONSOLE_URL }}
          NEXT_PUBLIC_EMBED_LIB_URL: ${{ var.NEXT_PUBLIC_EMBED_LIB_URL }}
          ALLOWED_HOSTNAMES: ${{ var.ALLOWED_HOSTNAMES }}
          CRON_API_KEY: ${{ var.CRON_API_KEY }}
          RESERVED_SUBDOMAINS: ${{ var.RESERVED_SUBDOMAINS }}
          CRON_ENABLE_APP_SYNC: ${{ var.CRON_ENABLE_APP_SYNC }}
          PLAIN_API_URL: ${{ var.PLAIN_API_URL }}
          GOOGLE_LOGIN_ENABLED: ${{ var.GOOGLE_LOGIN_ENABLED }}
          EMAIL_FROM: ${{ var.EMAIL_FROM }}
          NEXT_PUBLIC_FORMBRICKS_HOST_URL: ${{ var.NEXT_PUBLIC_FORMBRICKS_HOST_URL }}
          EMAIL_FROM_NAME: ${{ var.EMAIL_FROM_NAME }}
          EMAIL_SERVER_HOST: ${{ var.EMAIL_SERVER_HOST }}
          EMAIL_SERVER_PORT: ${{ var.EMAIL_SERVER_PORT }}
          NEXT_PUBLIC_APP_NAME: ${{ var.NEXT_PUBLIC_APP_NAME }}
          NEXT_PUBLIC_TEAM_IMPERSONATION: ${{ var.NEXT_PUBLIC_TEAM_IMPERSONATION }}
          NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS: ${{ var.NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS }}
          NEXT_PUBLIC_COMPANY_NAME: ${{ var.NEXT_PUBLIC_COMPANY_NAME }}
          NEXT_PUBLIC_ORGANIZATIONS_MIN_SELF_SERVE_SEATS: ${{ var.NEXT_PUBLIC_ORGANIZATIONS_MIN_SELF_SERVE_SEATS }}
          NEXT_PUBLIC_ORGANIZATIONS_SELF_SERVE_PRICE_NEW: ${{ var.NEXT_PUBLIC_ORGANIZATIONS_SELF_SERVE_PRICE_NEW }}
          E2E_TEST_CALCOM_QA_EMAIL: ${{ var.E2E_TEST_CALCOM_QA_EMAIL }}
          CALCOM_CREDENTIAL_SYNC_HEADER_NAME: ${{ var.CALCOM_CREDENTIAL_SYNC_HEADER_NAME }}
          TASKER_ENABLE_WEBHOOKS: ${{ var.TASKER_ENABLE_WEBHOOKS }}
          TASKER_ENABLE_EMAILS: ${{ var.TASKER_ENABLE_EMAILS }}
          NEXT_PUBLIC_INVALIDATE_AVAILABLE_SLOTS_ON_BOOKING_FORM: ${{ var.NEXT_PUBLIC_INVALIDATE_AVAILABLE_SLOTS_ON_BOOKING_FORM }}
          NEXT_PUBLIC_QUICK_AVAILABILITY_ROLLOUT: ${{ var.NEXT_PUBLIC_QUICK_AVAILABILITY_ROLLOUT }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ var.NEXT_PUBLIC_SENTRY_DSN }}
      - name: 🔐 Get ID token for Azure auth
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      - name: 🚀 Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        id: builddeploy
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_MOSS_0210CC310 }}
          action: "upload"
          # Point to the built output folder inside your monorepo
          app_location: "apps/web"                         # where your Next.js app lives
          output_location: "apps/web/out"                  # where Next.js exports static site (after `next export`)
          api_location: ""                                 # optional
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
